'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucMenu

    '''<summary>
    '''tblMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMenu As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''WebExplorerBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebExplorerBar1 As Global.Infragistics.Web.UI.NavigationControls.WebExplorerBar

    '''<summary>
    '''WebExplorerBar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebExplorerBar2 As Global.Infragistics.Web.UI.NavigationControls.WebExplorerBar
End Class
