'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucSchedule

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RoundedCornersExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoundedCornersExtender1 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''RoundedCornersExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoundedCornersExtender2 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''RoundedCornersExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoundedCornersExtender3 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''PanelScheduleAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelScheduleAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucScheduleAdd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucScheduleAdd1 As Global.OSSAARankings.ucScheduleAdd

    '''<summary>
    '''PanelScheduleTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelScheduleTeam As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucScheduleListSmall1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucScheduleListSmall1 As Global.OSSAARankings.ucScheduleListSmall

    '''<summary>
    '''space1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents space1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelScheduleList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelScheduleList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessageSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageSpecial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucScheduleList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucScheduleList1 As Global.OSSAARankings.ucScheduleList
End Class
