<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/ossaa/SiteOSSAA.Master" CodeBehind="Media.aspx.vb" Inherits="OSSAARankings.Media" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<table style="width: 100%;">
    <tbody>
        <tr align="left">
            <td><img alt="" style="border: 1px solid;" src="http://ossaarankings.mobi/ossaa/images/OSSAAMediaInformationS.png" /></td>
        </tr>
        <tr align="left">
            <td style="font-size: medium; height: 26px; font-family: Arial; color: white; background-color: maroon;"><strong>&nbsp;GENERAL MEDIA INFORMATION</strong></td>
        </tr>
        <tr align="left">
            <td><span style="font-size: 14px; font-family: arial;"><strong>We recognize the interest and promotion generated by media coverage and the recognition given to the achievements of school teams and student-athletes. Therefore, the OSSAA has established guidelines to assist media with the requesting Playoff Passes and other information listed below. </strong></span></td>
        </tr>
        <tr align="left">
            <td class="style1">&nbsp;<span style="font-family: Arial;"><strong><img alt="" width="10" height="10" src="button.gif" />&nbsp;</strong><strong><span><strong><span><strong><a href="http://ossaarankings.mobi/docs/2015-16/MiscForms/MF_2015-16_MediaGuidelines.pdf?id=3" target="_blank"><span><strong>OSSAA Media Guidelines</strong></span></a></strong></span></strong></span></strong></span></td>
        </tr>
        <tr align="left">
            <td class="style1">
                &nbsp;<span style="font-family: Arial;"><span style="text-align: center;"><strong><img alt="" width="10" height="10" src="button.gif" style="text-align: center;" /></strong></span><strong>&nbsp;</strong><span style="text-align: center;"><a href="http://ossaarankings.mobi/docs/2015-16/MiscForms/MF_2015-16_PlayoffPassForm.pdf?id=5" target="_blank"><strong>OSSAA Playoff Pass Request&nbsp;</strong></a></span></span><br />
                <strong><span style="font-size: 14px; font-family: arial;"><a href="mailto:vsiven@ossaa.com" target="_blank" class="ApplyClass"><strong><span style="font-size: 14px; font-family: arial;"></span></strong></a></span></strong>
            </td>
        </tr>
        <tr align="left">
            <td>&nbsp;</td>
        </tr>
        <tr align="left">
            <td>&nbsp;</td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;<strong>All Inquiries:</strong></span></td>
        </tr>
        <tr align="left">
            <td>
                <span style="font-family: arial; font-size: 13px;">
                    &nbsp;Van Shea Iven<br />
                </span>
            </td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;Media Relations Director</span></td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;Oklahoma Secondary School Activities Association</span></td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;7300 North Broadway Extension</span></td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;Oklahoma City, OK 73113</span></td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;405.840.1116 (Phone)</span></td>
        </tr>
        <tr align="left">
            <td><span style="font-family: arial; font-size: 13px;">&nbsp;vsiven@ossaa.com</span></td>
        </tr>
        <tr align="left">
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>

</asp:Content>
