'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PlayoffAvailabilityFB

    '''<summary>
    '''updProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updProgress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficialInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficialInfo1 As Global.OSSAARankings.OfficialInfo

    '''<summary>
    '''cmdGoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGoBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageStep1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgArrowsStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrowsStep1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelStep1Collapsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep1Collapsable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageStep2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgArrowsStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrowsStep2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelStep2Collapsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep2Collapsable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblInstructionsStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstructionsStep2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cb6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb6A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb2A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb5A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb4A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb3A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb8Man control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb8Man As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panelStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageStep3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgArrowsStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrowsStep3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelStep3Collapsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep3Collapsable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblInstructionsStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstructionsStep3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWeek1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeek1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWeek11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblWeek2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeek2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWeek21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek21 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek22 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek23 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblWeek3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeek3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWeek31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek31 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek32 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblWeek4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeek4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWeek41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek41 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek42 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek43 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblWeek5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeek5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWeek51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek51 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbWeek52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWeek52 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panelStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageStep4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgArrowsStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrowsStep4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelStep4Collapsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep4Collapsable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblHomeTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHomeTeam As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboHomeTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboHomeTeam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAwayTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAwayTeam As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAwayTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAwayTeam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''panelStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageStep5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgArrowsStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrowsStep5 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelStep5Collapsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelStep5Collapsable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTeamConflict1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamConflict1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTeamConflict1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamConflict1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTeamConflict2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamConflict2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTeamConflict2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamConflict2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTeamConflict3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamConflict3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTeamConflict3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamConflict3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTeamConflict4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamConflict4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTeamConflict4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamConflict4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTeamConflict5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamConflict5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTeamConflict5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamConflict5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdSave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CollapsiblePanelExtenderStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtenderStep1 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''CollapsiblePanelExtenderStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtenderStep3 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''CollapsiblePanelExtenderStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtenderStep2 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''CollapsiblePanelExtenderStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtenderStep4 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''CollapsiblePanelExtenderStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtenderStep5 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
