'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrefEdit6A5ANoAJAX

    '''<summary>
    '''cmdBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistrictInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrictInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSiteManagerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteManagerEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSiteManagerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteManagerEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSiteManagerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteManagerPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSiteManagerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteManagerPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOSSAAID20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOSSAAID20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOfficialName20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialName20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialCity20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialCity20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialZip20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialZip20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOfficialMiles20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficialMiles20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chris control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chris As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ellen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ellen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl100 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature31 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature32 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature41 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature42 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature51 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature52 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSignature61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature61 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature62 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label
End Class
