'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registration1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''rowStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowStep As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''lblStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdGoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGoBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rowRegistrationThis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRegistrationThis As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''rowRegistrationThisOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRegistrationThisOK As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cbRegisteredThisSeasonOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRegisteredThisSeasonOK As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''rowRegistrationThisOOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRegistrationThisOOS As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''hlReciprocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlReciprocal As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbRegisteredThisSeasonOOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRegisteredThisSeasonOOS As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''rowRegistrationEver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRegistrationEver As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''rowRegistrationEver1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRegistrationEver1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cbRegisteredEver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRegisteredEver As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''rowSports1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSports1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''lblSportHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSportHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rowSports2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSports2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''tblSports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSports As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''imgBaseball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBaseball As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgBasketball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBasketball As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgFootball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFootball As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgSoccer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSoccer As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgTrack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTrack As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''cmdBaseball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBaseball As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdBasketball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBasketball As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdFootball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFootball As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdSoccer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSoccer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdTrack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdTrack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgFastPitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFastPitch As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgSlowPitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSlowPitch As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgVolleyball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVolleyball As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgWrestling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWrestling As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''cmdFastPitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFastPitch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdSlowPitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSlowPitch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdVolleyball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdVolleyball As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdWrestling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdWrestling As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdHome As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hlPopupBlicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPopupBlicker As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''rowMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowMessage As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rowButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowButtons As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cmdRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRegister As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdRegister1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRegister1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdGoHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGoHome As Global.System.Web.UI.WebControls.Button
End Class
